# 1. Entendimiento inicial de los datos

In [9]:
# Lista de columnas a castear según lo indica el Diccionario de Datos
#cast_columns_int = ["arrival_date_year","children","days_in_waiting_list","required_car_parking_spaces","total_of_special_requests","agent","company"]

#creacion de un nuevo dataframe que será transformado y limipiado
#reservation_df_clean=reservation_df
# Casteo columnas a string segun el diccionario de datos 
#convertir_string(cast_columns_int,reservation_df_clean)
# Casteo columnas a date segun el diccionario de datos 
#obtiene lista de columnas tipo "object"
#ion_df_clean.select_dtypes(include="object").columns
# limpieza columnas string
#eliminar_espacios(columns_object,reservation_df_clean)
#se eliminan duplicados
#reservation_df_clean = reservation_df_clean.drop_duplicates()

### Carga y limpieza de Datos

In [1]:
# Importación de librerías
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency


# transformación columnas a tipo entero
def convertir_string(cast_columns_int,df):
    for i in cast_columns_int:
        df[i]=(
        pd.to_numeric(df[i], errors="coerce")
          .round()
          .astype("Int64")
        )
# transformación columnas a tipo fecha
def convertir_date(cast_columns_date,df):
    for i in cast_columns_date:
        df[i]=(
        pd.to_datetime(df[i], errors="coerce")
        )

# limpieza columnas tipo string (object) 
def eliminar_espacios(columns_object,df):
    df[columns_object]=df[columns_object].apply(lambda x: x.str.strip())

In [2]:
# carga fuente insumo
users_df = pd.read_csv("data/users.csv")
declarations_df = pd.read_csv("data/declarations.csv")
projects_computed_df = pd.read_csv("data/projects_computed.csv")
projects_df = pd.read_csv("data/projects.csv")
subscriptions_df = pd.read_csv("data/subscriptions.csv")
tasks_computed_df = pd.read_csv("data/tasks_computed.csv")
tasks_df = pd.read_csv("data/tasks.csv")
teams_df = pd.read_csv("data/teams.csv")

In [6]:
# Dimensiones dataset
print(users_df.dtypes)
print(users_df.shape)

id            object
created_at    object
deleted_at    object
team_id       object
dtype: object
(20556, 4)

In [3]:
users_df.head(5)

,id,created_at,deleted_at,team_id
0,304f70f2-a7d9-4bfd-b487-dc6507e5c5af,2024-01-19 05:16:42.528591+00,2024-08-18 00:00:00.189885+00,ac24b4c2-64f5-491b-9a02-69122cb46cf3
1,5cf703dd-c528-41e2-9157-92cdf9cf04b8,2024-02-11 15:22:46.233984+00,2024-08-25 00:00:00.079552+00,c8284c83-69c2-4aac-911b-4b88f8bfad0d
2,73fb67b7-d25c-463c-9389-953bff9735d2,2024-05-13 14:42:41.88442+00,NaN,2543058a-0cb6-4250-9719-e897be52a8fd
3,9e1b82e3-22bd-4319-8a62-747c907796ef,2022-06-14 12:40:50.089706+00,NaN,f2a06e3f-e306-4056-b666-56542a73c394
4,4337efdc-c9db-4535-88e5-238771234466,2024-08-27 07:06:28.723676+00,NaN,a9955a9b-cd09-4bfc-8777-802fdafcab1a

In [ ]:
cast_columns_date = ["created_at","deleted_at"]
convertir_date(cast_columns_date,users_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,projects_computed_df)
cast_columns_date = ["subscribe_at","disabled_at","trial_start_at","trial_end_at"]
convertir_date(cast_columns_date,subscriptions_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,tasks_computed_df)
cast_columns_date = ["created_at","deleted_at"]
convertir_date(cast_columns_date,teams_df)
cast_columns_date = ["created_at","date"]
convertir_date(cast_columns_date,declarations_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,tasks_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,projects_df)

In [13]:
############################################################################

In [47]:
empleados_df = pd.merge(
    users_df, 
    teams_df, 
    how='left',
    left_on='team_id',
    right_on='id'
)
# Renombrar varias columnas
empleados_df = empleados_df.rename(columns={
    'id_x': 'empleado_id',
    'created_at_x': 'creacion_empleado',
    'deleted_at_x': 'eliminacion_empleado',
    'created_at_y': 'creacion_team',
    'deleted_at_y': 'eliminacion_team'
})
# Eliminar una columna
empleados_df = empleados_df.drop(columns=['id_y'])

In [48]:
empleados_df.head(3)

,empleado_id,creacion_empleado,eliminacion_empleado,team_id,creacion_team,eliminacion_team
0,304f70f2-a7d9-4bfd-b487-dc6507e5c5af,2024-01-19 05:16:42.528591+00:00,2024-08-18 00:00:00.189885+00:00,ac24b4c2-64f5-491b-9a02-69122cb46cf3,2024-01-19 05:16:42.528591+00:00,2024-08-18 00:00:00.189885+00:00
1,5cf703dd-c528-41e2-9157-92cdf9cf04b8,2024-02-11 15:22:46.233984+00:00,2024-08-25 00:00:00.079552+00:00,c8284c83-69c2-4aac-911b-4b88f8bfad0d,2024-02-11 15:22:46.233984+00:00,2024-08-25 00:00:00.079552+00:00
2,73fb67b7-d25c-463c-9389-953bff9735d2,2024-05-13 14:42:41.884420+00:00,NaT,2543058a-0cb6-4250-9719-e897be52a8fd,2023-12-04 10:34:33.692335+00:00,NaT

In [ ]:
print(tasks_df["id"].nunique())
print(tasks_computed_df["id"].nunique())

717470
628466

In [54]:
proyectos_df = pd.merge(
    tasks_df, 
    tasks_computed_df, 
    how='left',
    left_on='id',
    right_on='id'
)

In [62]:
proyectos_df.sample(4)

,id,created_at_x,is_container_x,parent_id_x,project_id_x,created_at_y,is_container_y,parent_id_y,project_id_y,planned_duration,elapsed_duration
667747,f4e319b4-efe6-4e70-b01b-4da06ede6783,2024-06-14 14:27:39.610310+00:00,f,2ea0cad8-0dff-408f-95df-f37467d5c97d,0134e49b-8a0b-4830-a6b0-68e5b5c9b2fc,2024-06-14,False,2ea0cad8-0dff-408f-95df-f37467d5c97d,0134e49b-8a0b-4830-a6b0-68e5b5c9b2fc,5h15m0s,1h45m0s
687663,1a8c9b20-ee96-4e1a-981e-43e7cc273b6f,2024-07-28 20:58:09.199470+00:00,f,e00706ee-c535-4f3a-ad9c-9a497fca915d,31559109-681e-4e5c-9842-03abbe9fe6eb,NaT,NaN,NaN,NaN,NaN,NaN
183747,71a2aab1-8c6f-454c-a42e-c708a26fce7b,2022-10-31 10:14:56.914557+00:00,f,NaN,fe26360f-5387-43f6-99ec-9fc89b9134e7,NaT,NaN,NaN,NaN,NaN,NaN
686176,6f604e85-c72f-4fec-afa3-fc4f22778049,2024-07-26 08:34:51.863357+00:00,f,8348b503-d1fd-4e88-9651-4a0c15a1eb13,c476d93c-3f10-4f69-9605-165163c13bc4,2024-07-26,False,8348b503-d1fd-4e88-9651-4a0c15a1eb13,c476d93c-3f10-4f69-9605-165163c13bc4,0s,0s

In [57]:
proyectos_df.shape

(717470, 11)