# 1. Entendimiento inicial de los datos

In [1]:
# Lista de columnas a castear según lo indica el Diccionario de Datos
#cast_columns_int = ["arrival_date_year","children","days_in_waiting_list","required_car_parking_spaces","total_of_special_requests","agent","company"]

#creacion de un nuevo dataframe que será transformado y limipiado
#reservation_df_clean=reservation_df
# Casteo columnas a string segun el diccionario de datos 
#convertir_string(cast_columns_int,reservation_df_clean)
# Casteo columnas a date segun el diccionario de datos 
#obtiene lista de columnas tipo "object"
#ion_df_clean.select_dtypes(include="object").columns
# limpieza columnas string
#eliminar_espacios(columns_object,reservation_df_clean)
#se eliminan duplicados
#reservation_df_clean = reservation_df_clean.drop_duplicates()

### Carga y limpieza de Datos

In [2]:
# Importación de librerías
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency


# transformación columnas a tipo entero
def convertir_string(cast_columns_int,df):
    for i in cast_columns_int:
        df[i]=(
        pd.to_numeric(df[i], errors="coerce")
          .round()
          .astype("Int64")
        )
# transformación columnas a tipo fecha
def convertir_date(cast_columns_date,df):
    for i in cast_columns_date:
        df[i]=(
        pd.to_datetime(df[i], errors="coerce")
        )

# limpieza columnas tipo string (object) 
def eliminar_espacios(columns_object,df):
    df[columns_object]=df[columns_object].apply(lambda x: x.str.strip())

In [3]:
# carga fuente insumo
users_df = pd.read_csv("data/users.csv")
declarations_df = pd.read_csv("data/declarations.csv")
projects_computed_df = pd.read_csv("data/projects_computed.csv")
projects_df = pd.read_csv("data/projects.csv")
subscriptions_df = pd.read_csv("data/subscriptions.csv")
tasks_computed_df = pd.read_csv("data/tasks_computed.csv")
tasks_df = pd.read_csv("data/tasks.csv")
teams_df = pd.read_csv("data/teams.csv")

In [4]:
# Dimensiones dataset
print(users_df.dtypes)
print(users_df.shape)

id            object
created_at    object
deleted_at    object
team_id       object
dtype: object
(20556, 4)

In [5]:
users_df.head(5)

,id,created_at,deleted_at,team_id
0,304f70f2-a7d9-4bfd-b487-dc6507e5c5af,2024-01-19 05:16:42.528591+00,2024-08-18 00:00:00.189885+00,ac24b4c2-64f5-491b-9a02-69122cb46cf3
1,5cf703dd-c528-41e2-9157-92cdf9cf04b8,2024-02-11 15:22:46.233984+00,2024-08-25 00:00:00.079552+00,c8284c83-69c2-4aac-911b-4b88f8bfad0d
2,73fb67b7-d25c-463c-9389-953bff9735d2,2024-05-13 14:42:41.88442+00,NaN,2543058a-0cb6-4250-9719-e897be52a8fd
3,9e1b82e3-22bd-4319-8a62-747c907796ef,2022-06-14 12:40:50.089706+00,NaN,f2a06e3f-e306-4056-b666-56542a73c394
4,4337efdc-c9db-4535-88e5-238771234466,2024-08-27 07:06:28.723676+00,NaN,a9955a9b-cd09-4bfc-8777-802fdafcab1a

In [6]:
cast_columns_date = ["created_at","deleted_at"]
convertir_date(cast_columns_date,users_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,projects_computed_df)
cast_columns_date = ["subscribe_at","disabled_at","trial_start_at","trial_end_at"]
convertir_date(cast_columns_date,subscriptions_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,tasks_computed_df)
cast_columns_date = ["created_at","deleted_at"]
convertir_date(cast_columns_date,teams_df)
cast_columns_date = ["created_at","date"]
convertir_date(cast_columns_date,declarations_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,tasks_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,projects_df)

In [7]:
############################################################################

In [8]:
#creacion tabla empleados
empleados_df = pd.merge(
    users_df, 
    teams_df, 
    how='left',
    left_on='team_id',
    right_on='id'
)
# Renombrar varias columnas
empleados_df = empleados_df.rename(columns={
    'id_x': 'empleado_id',
    'created_at_x': 'creacion_empleado',
    'deleted_at_x': 'eliminacion_empleado',
    'created_at_y': 'creacion_team',
    'deleted_at_y': 'eliminacion_team'
})
# Eliminar una columna
empleados_df = empleados_df.drop(columns=['id_y']).drop_duplicates()

In [9]:
# creacion tabla tareas
tareas_df = pd.merge(
    tasks_df, 
    tasks_computed_df, 
    how='left',
    left_on='id',
    right_on='id'
)
tareas_df = tareas_df.rename(columns={
    'id': 'tarea_id',
    'created_at_x': 'creacion_tarea',
    'is_container_x': 'is_subtarea',
    'parent_id_x':'parent_id',
    'project_id_x': 'proyecto_id',
    'created_at_y': 'creacion_tarea_date',
    'planned_duration':'duracion_planeada_tarea',
    'elapsed_duration':'duracion_trascurrida_tarea'
})
# Eliminar una columna
tareas_df = tareas_df.drop(columns=['is_container_y','parent_id_y','project_id_y']).drop_duplicates()

In [10]:
tareas_df.sample(3)

,tarea_id,creacion_tarea,is_subtarea,parent_id,proyecto_id,creacion_tarea_date,duracion_planeada_tarea,duracion_trascurrida_tarea
381266,72399433-a663-476b-a419-3565cf88ccf3,2023-03-24 10:26:49.884087+00:00,f,NaN,4bf94bec-0b74-4d59-ab5e-f7bc27d96d56,2023-03-24,0s,0s
443012,0e613183-9317-4c8e-bda4-ab7a2a9754fa,2023-08-31 09:03:47.764423+00:00,f,716957b1-7c0e-4cd2-9385-be89e0015e02,adb92884-204a-409c-93cf-77dda68f8de9,2023-08-31,30m0s,0s
8702,04213335-0398-4845-a588-8c3841350032,2022-05-03 12:31:40.120079+00:00,f,NaN,297f5613-089e-4a7d-ae2e-b20deac1cd52,2022-05-03,0s,0s

In [11]:
#creacion tabla proyectos
proyectos_df = pd.merge(
    projects_df, 
    projects_computed_df, 
    how='left',
    left_on='id',
    right_on='id'
)

proyectos_df = proyectos_df.rename(columns={
    'id': 'proyecto_id',
    'created_at_x': 'creacion_proyecto',
    'team_id_x':'team_id',
    'created_at_y': 'creacion_proyecto_date',
    'team_id_y':'team_id_2',
    'planned_duration':'duracion_planeada_projecto',
    'elapsed_duration':'duracion_trascurrida_projecto'
}).drop_duplicates()
proyectos_df = proyectos_df.drop(columns=['team_id_2']).drop_duplicates()

In [12]:
proyectos_df.sample(3)

,proyecto_id,creacion_proyecto,team_id,creacion_proyecto_date,duracion_planeada_projecto,duracion_trascurrida_projecto
24583,e61ae55b-04e2-4593-8b29-735cee8bba17,2020-06-04 13:50:05.258000+00:00,f77e4d52-e646-4d4e-9e53-1da67d064871,2020-06-04,0s,12h15m0s
63781,9e78bdc9-5132-4717-8849-ff1bb5558d68,2024-05-29 07:31:57.876939+00:00,2543058a-0cb6-4250-9719-e897be52a8fd,NaT,NaN,NaN
56423,ccb7df57-bbf4-4463-b58c-fcfa7b0d98d7,2023-04-14 12:48:49.518744+00:00,5d5eeb9f-1d93-42e0-9b22-8097f72d4227,2023-04-14,0s,86h45m0s

In [13]:
#creacion tabla grupos
equipos_df = pd.merge(
    teams_df, 
    subscriptions_df, 
    how='left',
    left_on='id',
    right_on='team_id'
)
equipos_df = equipos_df.drop(columns=['team_id'])
equipos_df = equipos_df.rename(columns={
    'id': 'team_id',
    'deleted_at': 'eliminacion_grupo_bd',
    'created_at': 'creacion_grupo_bd',
    'subscribe_at':'fecha_subcripcion_grupo',
    'disabled_at': 'fecha_deshabilitacion_grupo',
    'status':'estado',
    'offer':'oferta',
    'trial_start_at':'inicio_prueba_en',
    'trial_end_at':'finalizacion_prueba_en'
}).drop_duplicates()

In [14]:
equipos_df.sample(3)

,team_id,creacion_grupo_bd,eliminacion_grupo_bd,fecha_subcripcion_grupo,fecha_deshabilitacion_grupo,estado,oferta,inicio_prueba_en,finalizacion_prueba_en
2200,9eb6ca95-1f3e-4163-be09-e116515b4135,2023-06-20 12:59:51.946715+00:00,2024-01-18 00:00:00.089853+00:00,NaT,2023-07-21 00:01:24.012897+00:00,disabled,time,2023-06-20 12:59:51.934989+00:00,2023-07-20 12:59:51.934990+00:00
121,f6c5913f-3648-494a-85e3-ae13ba860b9a,2021-07-20 08:33:01.065709+00:00,NaT,2022-09-30 22:00:00+00:00,NaT,active,budget,2021-07-20 08:33:01.099428+00:00,NaT
2420,db72d6b4-40bb-4928-b2f4-092af06bde25,2019-10-15 09:04:45.223000+00:00,2024-09-11 00:00:00.197370+00:00,2021-05-07 12:38:09+00:00,2024-03-14 22:54:09.167924+00:00,disabled,freemium,2020-03-29 12:49:40.985137+00:00,2020-04-29 12:49:40.985137+00:00

In [15]:
#creacion tabla tarea usuarios
tareas_empleados_df = pd.merge(
    tareas_df, 
    declarations_df, 
    how='left',
    left_on='tarea_id',
    right_on='task_id'
)
tareas_empleados_df = tareas_empleados_df.rename(columns={
    'duration': 'duracion_tarea',
    'source': 'fuente',
    'user_id':'empleado_id',
    'id':'id_registro',
    'created_at':'creacion_registro_bd'
})
tareas_empleados_df = tareas_empleados_df.drop(columns=['task_id']).drop_duplicates()

In [25]:
declarations_df.sample(5)

,id,created_at,date,duration,source,user_id,task_id
4240105,a52f077d-ba0e-4d62-94db-0d0598876082,2022-12-16 16:14:07.483770+00:00,2022-12-30,28800000000000,app,1f9fa027-8784-427d-b669-42110de8f572,97193f8e-e838-4c02-8d8e-7ae68ac64c05
2476023,3c9ed1de-32ac-4f3e-a560-78616296202d,2023-10-05 08:34:48.869609+00:00,2023-10-05,1800000000000,app,1931c13b-29ff-432b-aeab-730aa1d4752f,c091079b-7973-480d-ab30-358d715e83f7
705572,af432658-c097-4d65-a306-3504b58bb194,2022-08-29 07:30:37.355414+00:00,2022-08-24,25200000000000,bot,25e53bbb-a4d2-4d31-9183-a15b2cb0949c,7cf70512-0955-4d39-8cde-879495bc34ea
661220,3acaa291-2617-4679-9110-c0e0c2e4851f,2022-04-07 15:28:59.659654+00:00,2022-04-07,18000000000000,bot,b52d0fc7-410a-426d-9c4a-92c0e5b950ac,3b63d6cc-3ac9-4757-b916-b562025c002b
2079251,2c396b17-7a3a-4743-ae42-d66a4121fd25,2020-12-04 12:58:39.020509+00:00,2020-11-06,19800000000000,app,1f0e5ba3-fe4a-4357-8d25-c68bd6ccdfd4,dd6b8fb3-d9c9-463f-a29b-9859fb17eae9

In [17]:
tareas_empleados_projectos_df = pd.merge(
    tareas_empleados_df, 
    proyectos_df, 
    how='left',
    left_on='proyecto_id',
    right_on='proyecto_id'
)

In [18]:
tareas_empleados_projectos_df.sample(3)

,tarea_id,creacion_tarea,is_subtarea,parent_id,proyecto_id,creacion_tarea_date,duracion_planeada_tarea,duracion_trascurrida_tarea,id_registro,creacion_registro_bd,date,duracion_tarea,fuente,empleado_id,creacion_proyecto,team_id,creacion_proyecto_date,duracion_planeada_projecto,duracion_trascurrida_projecto
974686,a157fdee-3708-4bea-8b22-11e559ed7a71,2022-07-04 13:26:41.574500+00:00,f,NaN,2242d59c-b86f-42ad-b470-3170b246f716,2022-07-04,0s,19606h45m0s,3f20759f-cd53-4c4d-b1d8-0363bcb53be3,2022-07-08 15:59:49.083854+00:00,2021-02-23,2.520000e+13,import,b4f6d55f-0904-4ddf-831b-3fe4408669b1,2022-07-04 13:26:41.574500+00:00,134d47e7-61cd-49d7-b866-f37dc2435446,2022-07-04,0s,33730h0m0s
4832215,8c0c0cef-066b-4f59-bdf8-34b46ef8e940,2024-06-24 15:05:14.572636+00:00,f,78ccfe4e-7c56-4547-8180-184f0a074e7f,91e98d7e-f214-45ba-ac0a-6579d8c8e1ff,2024-06-24,120h0m0s,16h15m0s,f9dce28f-cf12-498a-8dec-f98bbaa9b58d,2024-09-04 13:38:06.849148+00:00,2024-09-06,3.600000e+12,app,ba4f619c-0a64-4c95-81f9-dd95d68c052d,2024-06-24 15:05:14.526404+00:00,75adb87e-0a05-4ec8-98d4-0a6162f972f2,2024-06-24,152h0m0s,59h30m0s
3275913,8ea016c3-7458-44df-a0bf-741b1d48703d,2023-06-08 09:38:40.027578+00:00,f,NaN,81ceb5b3-5d20-439d-b43b-03b2c5be134c,2023-06-08,0s,2115h30m0s,eaa36fb4-1ec3-45ee-86c9-6e40ca2eb2bb,2023-11-14 13:32:22.768863+00:00,2023-03-07,1.350000e+13,app,6565b7ff-88f3-4563-9027-4e18d227820c,2023-06-07 08:51:35.073149+00:00,4fe6c2f9-a3ad-4be2-8bbd-1c4fcf8f8659,2023-06-07,0s,32198h0m0s

In [19]:
maestra_df = pd.merge(
    tareas_empleados_projectos_df, 
    equipos_df, 
    how='left',
    left_on='team_id',
    right_on='team_id'
)

In [24]:
maestra_df.dtypes

tarea_id                                      object
creacion_tarea                   datetime64[ns, UTC]
is_subtarea                                   object
parent_id                                     object
proyecto_id                                   object
creacion_tarea_date                   datetime64[ns]
duracion_planeada_tarea                       object
duracion_trascurrida_tarea                    object
id_registro                                   object
creacion_registro_bd             datetime64[ns, UTC]
date                                  datetime64[ns]
duracion_tarea                               float64
fuente                                        object
empleado_id                                   object
creacion_proyecto                datetime64[ns, UTC]
team_id                                       object
creacion_proyecto_date                datetime64[ns]
duracion_planeada_projecto                    object
duracion_trascurrida_projecto                 object
creacion_grupo_bd                datetime64[ns, UTC]
eliminacion_grupo_bd             datetime64[ns, UTC]
fecha_subcripcion_grupo          datetime64[ns, UTC]
fecha_deshabilitacion_grupo      datetime64[ns, UTC]
estado                                        object
oferta                                        object
inicio_prueba_en                 datetime64[ns, UTC]
finalizacion_prueba_en           datetime64[ns, UTC]
dtype: object

In [20]:
#cambio doomie

In [21]:
df=maestra_df[(maestra_df["proyecto_id"]=="cddd00a8-691c-412b-8dbf-13d2599096f4") & (tareas_empleados_projectos_df["tarea_id"]=="00015d04-66ca-41f0-8a9a-40dc49fd029d")].sort_values(by='creacion_tarea')

In [22]:
df.to_csv("maestra.csv",index=False, sep=';')