# 1. Entendimiento inicial de los datos

In [89]:
# Lista de columnas a castear según lo indica el Diccionario de Datos
#cast_columns_int = ["arrival_date_year","children","days_in_waiting_list","required_car_parking_spaces","total_of_special_requests","agent","company"]

#creacion de un nuevo dataframe que será transformado y limipiado
#reservation_df_clean=reservation_df
# Casteo columnas a string segun el diccionario de datos 
#convertir_string(cast_columns_int,reservation_df_clean)
# Casteo columnas a date segun el diccionario de datos 
#obtiene lista de columnas tipo "object"
#ion_df_clean.select_dtypes(include="object").columns
# limpieza columnas string
#eliminar_espacios(columns_object,reservation_df_clean)
#se eliminan duplicados
#reservation_df_clean = reservation_df_clean.drop_duplicates()

### Carga y limpieza de Datos

In [90]:
# Importación de librerías
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency


# transformación columnas a tipo entero
def convertir_string(cast_columns_int,df):
    for i in cast_columns_int:
        df[i]=(
        pd.to_numeric(df[i], errors="coerce")
          .round()
          .astype("Int64")
        )
# transformación columnas a tipo fecha
def convertir_date(cast_columns_date,df):
    for i in cast_columns_date:
        df[i]=(
        pd.to_datetime(df[i], errors="coerce")
        )

# limpieza columnas tipo string (object) 
def eliminar_espacios(columns_object,df):
    df[columns_object]=df[columns_object].apply(lambda x: x.str.strip())

In [91]:
# carga fuente insumo
users_df = pd.read_csv("data/users.csv")
declarations_df = pd.read_csv("data/declarations.csv")
projects_computed_df = pd.read_csv("data/projects_computed.csv")
projects_df = pd.read_csv("data/projects.csv")
subscriptions_df = pd.read_csv("data/subscriptions.csv")
tasks_computed_df = pd.read_csv("data/tasks_computed.csv")
tasks_df = pd.read_csv("data/tasks.csv")
teams_df = pd.read_csv("data/teams.csv")

In [92]:
# Dimensiones dataset
print(users_df.dtypes)
print(users_df.shape)

id            object
created_at    object
deleted_at    object
team_id       object
dtype: object
(20556, 4)

In [93]:
users_df.head(5)

,id,created_at,deleted_at,team_id
0,304f70f2-a7d9-4bfd-b487-dc6507e5c5af,2024-01-19 05:16:42.528591+00,2024-08-18 00:00:00.189885+00,ac24b4c2-64f5-491b-9a02-69122cb46cf3
1,5cf703dd-c528-41e2-9157-92cdf9cf04b8,2024-02-11 15:22:46.233984+00,2024-08-25 00:00:00.079552+00,c8284c83-69c2-4aac-911b-4b88f8bfad0d
2,73fb67b7-d25c-463c-9389-953bff9735d2,2024-05-13 14:42:41.88442+00,NaN,2543058a-0cb6-4250-9719-e897be52a8fd
3,9e1b82e3-22bd-4319-8a62-747c907796ef,2022-06-14 12:40:50.089706+00,NaN,f2a06e3f-e306-4056-b666-56542a73c394
4,4337efdc-c9db-4535-88e5-238771234466,2024-08-27 07:06:28.723676+00,NaN,a9955a9b-cd09-4bfc-8777-802fdafcab1a

In [94]:
cast_columns_date = ["created_at","deleted_at"]
convertir_date(cast_columns_date,users_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,projects_computed_df)
cast_columns_date = ["subscribe_at","disabled_at","trial_start_at","trial_end_at"]
convertir_date(cast_columns_date,subscriptions_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,tasks_computed_df)
cast_columns_date = ["created_at","deleted_at"]
convertir_date(cast_columns_date,teams_df)
cast_columns_date = ["created_at","date"]
convertir_date(cast_columns_date,declarations_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,tasks_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,projects_df)

In [95]:
############################################################################

In [96]:
#creacion tabla empleados
empleados_df = pd.merge(
    users_df, 
    teams_df, 
    how='left',
    left_on='team_id',
    right_on='id'
)
# Renombrar varias columnas
empleados_df = empleados_df.rename(columns={
    'id_x': 'empleado_id',
    'created_at_x': 'creacion_empleado',
    'deleted_at_x': 'eliminacion_empleado',
    'created_at_y': 'creacion_team',
    'deleted_at_y': 'eliminacion_team'
})
# Eliminar una columna
empleados_df = empleados_df.drop(columns=['id_y']).drop_duplicates()

In [97]:
# creacion tabla tareas
tareas_df = pd.merge(
    tasks_df, 
    tasks_computed_df, 
    how='left',
    left_on='id',
    right_on='id'
)
tareas_df = tareas_df.rename(columns={
    'id': 'tarea_id',
    'created_at_x': 'creacion_tarea',
    'is_container_x': 'is_subtarea',
    'parent_id_x':'parent_id',
    'project_id_x': 'proyecto_id',
    'created_at_y': 'creacion_tarea_date',
    'planned_duration':'duracion_planeada',
    'elapsed_duration':'duracion_trascurrida'
})
# Eliminar una columna
tareas_df = tareas_df.drop(columns=['is_container_y','parent_id_y','project_id_y']).drop_duplicates()

In [98]:
tareas_df.sample(3)

,tarea_id,creacion_tarea,is_subtarea,parent_id,proyecto_id,creacion_tarea_date,duracion_planeada,duracion_trascurrida
580303,e7adf2d2-425a-49f5-bb17-60ee9e00ec5e,2024-02-01 14:28:06.385248+00:00,f,0e8fed6d-f008-49d1-8c1e-dcb0d69eac66,9b2e2014-4d70-49a3-bb1e-4c9a1e77af1a,2024-02-01,0s,0s
499919,08dd00d1-ab68-47cd-8f79-9b8a36432600,2023-12-13 15:29:05.821537+00:00,f,fad63e9c-bb03-48f6-8590-a8faa9384146,89cfa3e0-88c8-44be-9e8b-a41aac437be0,2023-12-13,0s,0s
206612,6d3081c1-9b2c-4626-aea0-b401ea56197e,2022-02-16 07:05:54.359383+00:00,t,NaN,6f2aafd2-a8ee-4d73-a99b-89e80da05d18,NaT,NaN,NaN

In [99]:
#creacion tabla proyectos
proyectos_df = pd.merge(
    projects_df, 
    projects_computed_df, 
    how='left',
    left_on='id',
    right_on='id'
)

proyectos_df = proyectos_df.rename(columns={
    'id': 'proyecto_id',
    'created_at_x': 'creacion_proyecto',
    'team_id_x':'team_id',
    'created_at_y': 'creacion_proyecto_date',
    'team_id_y':'team_id_2',
    'planned_duration':'duracion_planeada',
    'elapsed_duration':'duracion_trascurrida'
}).drop_duplicates()

In [100]:
#creacion tabla grupos
equipos_df = pd.merge(
    teams_df, 
    subscriptions_df, 
    how='left',
    left_on='id',
    right_on='team_id'
)
equipos_df = equipos_df.drop(columns=['team_id'])
equipos_df = equipos_df.rename(columns={
    'id': 'team_id',
    'deleted_at': 'eliminacion_grupo_bd',
    'created_at': 'creacion_grupo_bd',
    'subscribe_at':'fecha_subcripcion_grupo',
    'disabled_at': 'fecha_deshabilitacion_grupo',
    'status':'estado',
    'offer':'oferta',
    'trial_start_at':'inicio_prueba_en',
    'trial_end_at':'finalizacion_prueba_en'
}).drop_duplicates()

In [101]:
#creacion tabla tarea usuarios
tareas_empleados_df = pd.merge(
    tareas_df, 
    declarations_df, 
    how='left',
    left_on='tarea_id',
    right_on='task_id'
)
tareas_empleados_df = tareas_empleados_df.rename(columns={
    'duration': 'duracion_tarea',
    'source': 'fuente',
    'user_id':'empleado_id',
    'id':'id_registro',
    'created_at':'creacion_registro_bd'
})
tareas_empleados_df = tareas_empleados_df.drop(columns=['task_id']).drop_duplicates()

In [103]:
tareas_empleados_df.sample()

,tarea_id,creacion_tarea,is_subtarea,parent_id,proyecto_id,creacion_tarea_date,duracion_planeada,duracion_trascurrida,id_registro,creacion_registro_bd,date,duracion_tarea,fuente,empleado_id
3339058,82c505eb-15a8-4579-ae8f-5da1d80fb0ec,2022-03-25 07:47:29.559700+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2022-03-25,0s,9963h48m0s,12af0a2e-c8f8-468b-895a-604d234ec376,2023-11-27 05:26:39.129955+00:00,2023-11-29,2.880000e+13,app,5dda5b48-f64b-4c73-854c-e9d8a38ac8e2

In [104]:
tareas_empleados_df[tareas_empleados_df["proyecto_id"]=="e0ac350b-be84-4c63-aef8-2914e4d6f421"].sort_values(by='creacion_tarea')

,tarea_id,creacion_tarea,is_subtarea,parent_id,proyecto_id,creacion_tarea_date,duracion_planeada,duracion_trascurrida,id_registro,creacion_registro_bd,date,duracion_tarea,fuente,empleado_id
3337670,82c505eb-15a8-4579-ae8f-5da1d80fb0ec,2022-03-25 07:47:29.559700+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2022-03-25,0s,9963h48m0s,3e8fb1a1-5931-4277-bc29-30c2c94eaae5,2023-07-21 06:55:16.287696+00:00,2023-07-18,2.880000e+13,app,0e2502d8-9f54-4ad7-bf31-54a690716346
3338770,82c505eb-15a8-4579-ae8f-5da1d80fb0ec,2022-03-25 07:47:29.559700+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2022-03-25,0s,9963h48m0s,0d5aca82-af21-4337-b1bc-b3a158a3e021,2023-03-21 08:32:58.790321+00:00,2023-03-20,2.880000e+13,app,5dda5b48-f64b-4c73-854c-e9d8a38ac8e2
3338769,82c505eb-15a8-4579-ae8f-5da1d80fb0ec,2022-03-25 07:47:29.559700+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2022-03-25,0s,9963h48m0s,5cfe03b8-1ba0-46eb-9e2a-dae064fb77b6,2023-03-21 08:32:43.408741+00:00,2023-03-17,2.880000e+13,app,5dda5b48-f64b-4c73-854c-e9d8a38ac8e2
3338768,82c505eb-15a8-4579-ae8f-5da1d80fb0ec,2022-03-25 07:47:29.559700+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2022-03-25,0s,9963h48m0s,f4099905-4b13-4364-a497-4c519cbf0c3f,2023-03-17 06:36:01.992334+00:00,2023-03-16,2.880000e+13,app,5dda5b48-f64b-4c73-854c-e9d8a38ac8e2
3338767,82c505eb-15a8-4579-ae8f-5da1d80fb0ec,2022-03-25 07:47:29.559700+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2022-03-25,0s,9963h48m0s,5a313fb9-1f91-40c7-825f-90423bde4d12,2023-03-16 06:38:21.309568+00:00,2023-03-15,2.880000e+13,app,5dda5b48-f64b-4c73-854c-e9d8a38ac8e2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3339654,345bfc20-5145-4c22-9f3f-b4032aa1beee,2023-06-27 08:36:20.186570+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2023-06-27,0s,2709h0m0s,69c1ed4e-59d5-4668-8673-4e9a29a9639f,2023-09-29 11:42:13.414392+00:00,2023-09-21,7.200000e+12,app,f10bb94a-81e9-4ee8-91f8-b1f4dd3a87f5
3339653,345bfc20-5145-4c22-9f3f-b4032aa1beee,2023-06-27 08:36:20.186570+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2023-06-27,0s,2709h0m0s,7bdb9fea-2f76-4139-ad33-65d2bbb55b6f,2023-09-29 11:42:46.617160+00:00,2023-09-29,7.200000e+12,app,f10bb94a-81e9-4ee8-91f8-b1f4dd3a87f5
3339652,345bfc20-5145-4c22-9f3f-b4032aa1beee,2023-06-27 08:36:20.186570+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2023-06-27,0s,2709h0m0s,bfc0f11e-bf2e-437a-958e-e692aec3ee1e,2023-09-29 11:42:13.414392+00:00,2023-09-27,7.200000e+12,app,f10bb94a-81e9-4ee8-91f8-b1f4dd3a87f5
3339650,345bfc20-5145-4c22-9f3f-b4032aa1beee,2023-06-27 08:36:20.186570+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2023-06-27,0s,2709h0m0s,6dc346b3-6e15-4a56-ac54-0c04b529ee61,2023-09-29 11:42:13.414392+00:00,2023-09-25,7.200000e+12,app,f10bb94a-81e9-4ee8-91f8-b1f4dd3a87f5
3339988,345bfc20-5145-4c22-9f3f-b4032aa1beee,2023-06-27 08:36:20.186570+00:00,f,NaN,e0ac350b-be84-4c63-aef8-2914e4d6f421,2023-06-27,0s,2709h0m0s,cc98b23d-39e8-42f2-bfa9-528b7e794300,2023-07-05 05:37:34.308797+00:00,2023-07-04,2.880000e+13,app,63a0da95-cae7-42f9-aa8c-9740b7c1bb1e