# 1. Entendimiento inicial de los datos

In [125]:
# Lista de columnas a castear según lo indica el Diccionario de Datos
#cast_columns_int = ["arrival_date_year","children","days_in_waiting_list","required_car_parking_spaces","total_of_special_requests","agent","company"]

#creacion de un nuevo dataframe que será transformado y limipiado
#reservation_df_clean=reservation_df
# Casteo columnas a string segun el diccionario de datos 
#convertir_string(cast_columns_int,reservation_df_clean)
# Casteo columnas a date segun el diccionario de datos 
#obtiene lista de columnas tipo "object"
#ion_df_clean.select_dtypes(include="object").columns
# limpieza columnas string
#eliminar_espacios(columns_object,reservation_df_clean)
#se eliminan duplicados
#reservation_df_clean = reservation_df_clean.drop_duplicates()

### Carga y limpieza de Datos

In [126]:
# Importación de librerías
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency


# transformación columnas a tipo entero
def convertir_string(cast_columns_int,df):
    for i in cast_columns_int:
        df[i]=(
        pd.to_numeric(df[i], errors="coerce")
          .round()
          .astype("Int64")
        )
# transformación columnas a tipo fecha
def convertir_date(cast_columns_date,df):
    for i in cast_columns_date:
        df[i]=(
        pd.to_datetime(df[i], errors="coerce")
        )

# limpieza columnas tipo string (object) 
def eliminar_espacios(columns_object,df):
    df[columns_object]=df[columns_object].apply(lambda x: x.str.strip())

In [127]:
# carga fuente insumo
users_df = pd.read_csv("data/users.csv")
declarations_df = pd.read_csv("data/declarations.csv")
projects_computed_df = pd.read_csv("data/projects_computed.csv")
projects_df = pd.read_csv("data/projects.csv")
subscriptions_df = pd.read_csv("data/subscriptions.csv")
tasks_computed_df = pd.read_csv("data/tasks_computed.csv")
tasks_df = pd.read_csv("data/tasks.csv")
teams_df = pd.read_csv("data/teams.csv")

In [128]:
# Dimensiones dataset
print(users_df.dtypes)
print(users_df.shape)

id            object
created_at    object
deleted_at    object
team_id       object
dtype: object
(20556, 4)

In [129]:
users_df.head(5)

,id,created_at,deleted_at,team_id
0,304f70f2-a7d9-4bfd-b487-dc6507e5c5af,2024-01-19 05:16:42.528591+00,2024-08-18 00:00:00.189885+00,ac24b4c2-64f5-491b-9a02-69122cb46cf3
1,5cf703dd-c528-41e2-9157-92cdf9cf04b8,2024-02-11 15:22:46.233984+00,2024-08-25 00:00:00.079552+00,c8284c83-69c2-4aac-911b-4b88f8bfad0d
2,73fb67b7-d25c-463c-9389-953bff9735d2,2024-05-13 14:42:41.88442+00,NaN,2543058a-0cb6-4250-9719-e897be52a8fd
3,9e1b82e3-22bd-4319-8a62-747c907796ef,2022-06-14 12:40:50.089706+00,NaN,f2a06e3f-e306-4056-b666-56542a73c394
4,4337efdc-c9db-4535-88e5-238771234466,2024-08-27 07:06:28.723676+00,NaN,a9955a9b-cd09-4bfc-8777-802fdafcab1a

In [130]:
cast_columns_date = ["created_at","deleted_at"]
convertir_date(cast_columns_date,users_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,projects_computed_df)
cast_columns_date = ["subscribe_at","disabled_at","trial_start_at","trial_end_at"]
convertir_date(cast_columns_date,subscriptions_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,tasks_computed_df)
cast_columns_date = ["created_at","deleted_at"]
convertir_date(cast_columns_date,teams_df)
cast_columns_date = ["created_at","date"]
convertir_date(cast_columns_date,declarations_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,tasks_df)
cast_columns_date = ["created_at"]
convertir_date(cast_columns_date,projects_df)

In [131]:
############################################################################

In [132]:
#creacion tabla empleados
empleados_df = pd.merge(
    users_df, 
    teams_df, 
    how='left',
    left_on='team_id',
    right_on='id'
)
# Renombrar varias columnas
empleados_df = empleados_df.rename(columns={
    'id_x': 'empleado_id',
    'created_at_x': 'creacion_empleado',
    'deleted_at_x': 'eliminacion_empleado',
    'created_at_y': 'creacion_team',
    'deleted_at_y': 'eliminacion_team'
})
# Eliminar una columna
empleados_df = empleados_df.drop(columns=['id_y']).drop_duplicates()

In [133]:
# creacion tabla tareas
tareas_df = pd.merge(
    tasks_df, 
    tasks_computed_df, 
    how='left',
    left_on='id',
    right_on='id'
)
tareas_df = tareas_df.rename(columns={
    'id': 'tarea_id',
    'created_at_x': 'creacion_tarea',
    'is_container_x': 'is_subtarea',
    'parent_id_x':'parent_id',
    'project_id_x': 'proyecto_id',
    'created_at_y': 'creacion_tarea_date',
    'planned_duration':'duracion_planeada_tarea',
    'elapsed_duration':'duracion_trascurrida_tarea'
})
# Eliminar una columna
tareas_df = tareas_df.drop(columns=['is_container_y','parent_id_y','project_id_y']).drop_duplicates()

In [134]:
tareas_df.sample(3)

,tarea_id,creacion_tarea,is_subtarea,parent_id,proyecto_id,creacion_tarea_date,duracion_planeada_tarea,duracion_trascurrida_tarea
199121,532c2027-eec5-4ea6-bc7f-ca345ec8b586,2022-01-20 11:23:48.931529+00:00,f,2a8e905f-bc25-4166-8093-a94dbd0f4dfd,46902149-df60-4e39-8b99-9900eb61dbad,2022-01-20,0s,0s
108321,03313339-76ae-444a-8137-85c19b3f0885,2023-02-01 12:02:49.150502+00:00,f,NaN,275f2df6-a993-4143-9b7c-74da849e6d10,NaT,NaN,NaN
450499,6214ee61-2602-4b8a-968a-db7f9d4fc532,2023-09-14 12:43:12.843777+00:00,f,5484f089-29de-4625-8f28-e4176fe92e37,caed3402-6542-4cfd-a6d7-a97056cbf3c7,2023-09-14,0s,0s

In [145]:
#creacion tabla proyectos
proyectos_df = pd.merge(
    projects_df, 
    projects_computed_df, 
    how='left',
    left_on='id',
    right_on='id'
)

proyectos_df = proyectos_df.rename(columns={
    'id': 'proyecto_id',
    'created_at_x': 'creacion_proyecto',
    'team_id_x':'team_id',
    'created_at_y': 'creacion_proyecto_date',
    'team_id_y':'team_id_2',
    'planned_duration':'duracion_planeada_projecto',
    'elapsed_duration':'duracion_trascurrida_projecto'
}).drop_duplicates()
proyectos_df = proyectos_df.drop(columns=['team_id_2']).drop_duplicates()

In [146]:
proyectos_df.sample(3)

,proyecto_id,creacion_proyecto,team_id,creacion_proyecto_date,duracion_planeada_projecto,duracion_trascurrida_projecto
51844,26416ab4-c763-42a8-bc28-d00b82cc95b6,2022-12-11 18:53:48.760278+00:00,7825383d-a2ce-48a2-bfeb-ba9966d2a829,2022-12-11,0s,1973h15m0s
943,686a998d-c339-4405-8c32-ae4bffc3b250,2024-01-17 11:13:45.404279+00:00,4f8a5eac-1c07-460d-ae48-21d6aa973bae,2024-01-17,0s,8h15m0s
12578,e5ebf731-3be2-49ad-bac1-a64a4926ca03,2022-07-19 16:18:18.953390+00:00,38701998-d5bf-4830-88ea-6aceb3f33bd5,2022-07-19,0s,0s

In [136]:
#creacion tabla grupos
equipos_df = pd.merge(
    teams_df, 
    subscriptions_df, 
    how='left',
    left_on='id',
    right_on='team_id'
)
equipos_df = equipos_df.drop(columns=['team_id'])
equipos_df = equipos_df.rename(columns={
    'id': 'team_id',
    'deleted_at': 'eliminacion_grupo_bd',
    'created_at': 'creacion_grupo_bd',
    'subscribe_at':'fecha_subcripcion_grupo',
    'disabled_at': 'fecha_deshabilitacion_grupo',
    'status':'estado',
    'offer':'oferta',
    'trial_start_at':'inicio_prueba_en',
    'trial_end_at':'finalizacion_prueba_en'
}).drop_duplicates()

In [137]:
equipos_df.sample(3)

,team_id,creacion_grupo_bd,eliminacion_grupo_bd,fecha_subcripcion_grupo,fecha_deshabilitacion_grupo,estado,oferta,inicio_prueba_en,finalizacion_prueba_en
38,65a6f707-3f49-4f72-af59-9f209d0eeaa8,2024-04-09 15:53:53.631988+00:00,NaT,2024-04-30 13:21:49+00:00,NaT,active,budget,2024-04-09 15:53:53.630953+00:00,2024-04-23 15:53:53.630954+00:00
240,d4413189-86bd-4deb-a3fa-4c27d839fc1f,2023-10-18 06:51:44.261514+00:00,NaT,2023-11-15 13:46:46+00:00,NaT,active,budget,2023-10-18 06:51:44.260395+00:00,2023-11-17 06:51:44.260396+00:00
8,eece6420-a43a-401c-afcf-52770f759a0a,2020-01-22 14:58:29.165105+00:00,2024-09-11 00:00:00.197370+00:00,NaT,2024-03-14 22:53:45.975954+00:00,disabled,freemium,2020-03-29 12:49:40.985137+00:00,2020-04-29 12:49:40.985137+00:00

In [138]:
#creacion tabla tarea usuarios
tareas_empleados_df = pd.merge(
    tareas_df, 
    declarations_df, 
    how='left',
    left_on='tarea_id',
    right_on='task_id'
)
tareas_empleados_df = tareas_empleados_df.rename(columns={
    'duration': 'duracion_tarea',
    'source': 'fuente',
    'user_id':'empleado_id',
    'id':'id_registro',
    'created_at':'creacion_registro_bd'
})
tareas_empleados_df = tareas_empleados_df.drop(columns=['task_id']).drop_duplicates()

In [147]:
tareas_empleados_df.sample(1)

,tarea_id,creacion_tarea,is_subtarea,parent_id,proyecto_id,creacion_tarea_date,duracion_planeada_tarea,duracion_trascurrida_tarea,id_registro,creacion_registro_bd,date,duracion_tarea,fuente,empleado_id
3430983,5cd23e7c-2df6-4f92-aa77-668dfdc64233,2023-07-27 14:00:59.468927+00:00,f,5554224c-5459-4451-b390-601df16bfae2,781dfc3c-b191-434b-9d98-ac638d54a1f4,2023-07-27,0s,0s,NaN,NaT,NaT,NaN,NaN,NaN

In [149]:
tareas_empleados_projectos_df = pd.merge(
    tareas_empleados_df, 
    proyectos_df, 
    how='left',
    left_on='proyecto_id',
    right_on='proyecto_id'
)

In [150]:
tareas_empleados_projectos_df.sample(3)

,tarea_id,creacion_tarea,is_subtarea,parent_id,proyecto_id,creacion_tarea_date,duracion_planeada_tarea,duracion_trascurrida_tarea,id_registro,creacion_registro_bd,date,duracion_tarea,fuente,empleado_id,creacion_proyecto,team_id,creacion_proyecto_date,duracion_planeada_projecto,duracion_trascurrida_projecto
3993241,926b84d1-74f8-40dc-94d1-cb5cdd7004d9,2024-01-05 10:32:05.746591+00:00,f,NaN,cff1418a-d4c3-4018-a306-888b90074035,2024-01-05,0s,439h33m0s,b9ce188a-2f62-41c4-afce-750c93b10fab,2024-05-31 15:48:23.220692+00:00,2024-05-30,5.760000e+12,app,806bf57a-4677-4adb-8b10-1832a2226f6d,2024-01-05 10:32:05.746591+00:00,db97c470-86c1-4238-830c-de416d9553dc,2024-01-05,0s,3309h6m0s
2768426,97193f8e-e838-4c02-8d8e-7ae68ac64c05,2022-03-25 07:52:35.544266+00:00,f,NaN,c7260136-1d3f-42f0-bc3d-ecc0074093d3,2022-03-25,0s,346722h39m14s,ea862170-98d1-42ef-bd32-e6602d41a0bf,2024-05-27 13:53:26.675380+00:00,2024-05-10,2.880000e+13,app,f438b8a6-128e-4118-8f84-a311b0902236,2022-03-25 07:52:35.544266+00:00,cad594d3-e120-4e64-88ba-02d755643bbc,2022-03-25,0s,409283h9m14s
1512318,4d83882f-d33e-47dd-97c2-48cd80882366,2022-09-02 21:19:59.016206+00:00,f,76a330bd-f2dd-46bb-9766-58bf1f533c59,f7614414-56ec-408d-97ba-51c64789ccd5,2022-09-02,0s,15h0m0s,3a3da50f-463c-4878-9c35-531a0fd858b1,2022-09-15 01:01:00.304153+00:00,2022-09-13,1.440000e+13,app,f0a1c9a2-cb76-41e5-9693-979344ec35c9,2022-07-14 17:12:48.528114+00:00,7da05482-71e3-4355-8e7d-69970361a1bd,2022-07-14,0s,98h30m0s

In [163]:
maestra_df = pd.merge(
    tareas_empleados_projectos_df, 
    equipos_df, 
    how='left',
    left_on='team_id',
    right_on='team_id'
)

In [162]:
#cambio doomie

In [159]:
df=maestra_df[(maestra_df["proyecto_id"]=="cddd00a8-691c-412b-8dbf-13d2599096f4") & (tareas_empleados_projectos_df["tarea_id"]=="00015d04-66ca-41f0-8a9a-40dc49fd029d")].sort_values(by='creacion_tarea')

In [160]:
df.to_csv("maestra.csv",index=False, sep=';')